/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.lexer;

import java.io.*;
import compiler.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhiteSpace(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscapeSeq(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFun(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNothing(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRef(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThen(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new20(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntegers(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TErroneousNumber(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharConst(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringLiteral(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNeq(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLteq(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGteq(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBr(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBr(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLAg(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRAg(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArrow(line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {12, 12, 3}, {13, 13, 4}, {32, 32, 5}, {34, 34, 6}, {35, 35, 7}, {36, 36, 8}, {39, 39, 9}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 44, 14}, {45, 45, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {92, 92, 24}, {93, 93, 25}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 27}, {105, 105, 32}, {106, 108, 27}, {109, 109, 33}, {110, 110, 34}, {111, 111, 35}, {112, 113, 27}, {114, 114, 36}, {115, 115, 27}, {116, 116, 37}, {117, 117, 27}, {118, 118, 38}, {119, 119, 39}, {120, 122, 27}, {123, 123, 40}, {125, 125, 41}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 42}, {12, 32, -2}, },
            {{9, 32, -2}, },
            {{32, 32, 43}, {33, 33, 44}, {34, 34, 45}, {35, 35, 46}, {36, 36, 47}, {37, 37, 48}, {38, 38, 49}, {40, 40, 50}, {41, 41, 51}, {42, 42, 52}, {43, 43, 53}, {44, 44, 54}, {45, 45, 55}, {46, 46, 56}, {47, 47, 57}, {48, 57, 58}, {58, 58, 59}, {59, 59, 60}, {60, 60, 61}, {61, 61, 62}, {62, 62, 63}, {63, 63, 64}, {64, 64, 65}, {65, 90, 66}, {91, 91, 67}, {92, 92, 68}, {93, 93, 69}, {94, 94, 70}, {95, 95, 71}, {96, 96, 72}, {97, 122, 73}, {123, 123, 74}, {124, 124, 75}, {125, 125, 76}, {126, 126, 77}, },
            {},
            {{0, 9, 78}, {10, 10, 79}, {11, 12, 78}, {13, 13, 80}, {14, 35, 78}, {36, 36, 81}, {37, 65535, 78}, },
            {{32, 32, 82}, {33, 33, 83}, {35, 35, 84}, {36, 36, 85}, {37, 37, 86}, {38, 38, 87}, {40, 40, 88}, {41, 41, 89}, {42, 42, 90}, {43, 43, 91}, {44, 44, 92}, {45, 45, 93}, {46, 46, 94}, {47, 47, 95}, {48, 57, 96}, {58, 58, 97}, {59, 59, 98}, {60, 60, 99}, {61, 61, 100}, {62, 62, 101}, {63, 63, 102}, {64, 64, 103}, {65, 90, 104}, {91, 91, 105}, {92, 92, 106}, {93, 93, 107}, {94, 94, 108}, {95, 95, 109}, {96, 96, 110}, {97, 122, 111}, {123, 123, 112}, {124, 124, 113}, {125, 125, 114}, {126, 126, 115}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 16}, {65, 90, 116}, {95, 95, 117}, {97, 122, 118}, },
            {},
            {},
            {{45, 45, 119}, {61, 61, 120}, },
            {},
            {{61, 61, 121}, },
            {{48, 57, 122}, {65, 90, 123}, {95, 95, 124}, {97, 122, 125}, },
            {},
            {{34, 34, 126}, {39, 39, 127}, {48, 48, 128}, {92, 92, 129}, {110, 110, 130}, {114, 114, 131}, {116, 116, 132}, {120, 120, 133}, },
            {},
            {{48, 95, -24}, {97, 109, 125}, {110, 110, 134}, {111, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 103, 125}, {104, 104, 135}, {105, 122, 125}, },
            {{48, 95, -24}, {97, 104, 125}, {105, 105, 136}, {106, 110, 125}, {111, 111, 137}, {112, 122, 125}, },
            {{48, 95, -24}, {97, 107, 125}, {108, 108, 138}, {109, 122, 125}, },
            {{48, 95, -24}, {97, 116, 125}, {117, 117, 139}, {118, 122, 125}, },
            {{48, 95, -24}, {97, 101, 125}, {102, 102, 140}, {103, 109, 125}, {110, 110, 141}, {111, 122, 125}, },
            {{48, 95, -24}, {97, 110, 125}, {111, 111, 142}, {112, 122, 125}, },
            {{48, 110, -35}, {111, 111, 143}, {112, 122, 125}, },
            {{48, 95, -24}, {97, 113, 125}, {114, 114, 144}, {115, 122, 125}, },
            {{48, 95, -24}, {97, 100, 125}, {101, 101, 145}, {102, 122, 125}, },
            {{48, 103, -30}, {104, 104, 146}, {105, 122, 125}, },
            {{48, 95, -24}, {97, 97, 147}, {98, 122, 125}, },
            {{48, 103, -30}, {104, 104, 148}, {105, 122, 125}, },
            {},
            {},
            {{9, 32, -2}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {},
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{34, 34, 149}, {39, 39, 150}, {48, 48, 151}, {92, 92, 152}, {110, 110, 153}, {114, 114, 154}, {116, 116, 155}, {120, 120, 156}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{0, 9, 157}, {10, 10, 158}, {11, 12, 157}, {13, 13, 159}, {14, 65535, 157}, },
            {{0, 65535, -80}, },
            {{0, 9, 157}, {10, 10, 160}, {11, 65535, -80}, },
            {{0, 35, 161}, {36, 36, 162}, {37, 65535, 161}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{34, 34, 164}, {39, 39, 165}, {48, 48, 166}, {92, 92, 167}, {110, 110, 168}, {114, 114, 169}, {116, 116, 170}, {120, 120, 171}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{65, 122, -18}, },
            {{65, 122, -18}, },
            {{65, 122, -18}, },
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 172}, {65, 70, 173}, {97, 102, 174}, },
            {{48, 95, -24}, {97, 99, 125}, {100, 100, 175}, {101, 122, 125}, },
            {{48, 95, -24}, {97, 97, 176}, {98, 122, 125}, },
            {{48, 95, -24}, {97, 117, 125}, {118, 118, 177}, {119, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 114, 125}, {115, 115, 178}, {116, 122, 125}, },
            {{48, 109, -28}, {110, 110, 179}, {111, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 115, 125}, {116, 116, 180}, {117, 122, 125}, },
            {{48, 99, -136}, {100, 100, 181}, {101, 122, 125}, },
            {{48, 115, -143}, {116, 116, 182}, {117, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 101, -34}, {102, 102, 183}, {103, 115, 125}, {116, 116, 184}, {117, 122, 125}, },
            {{48, 100, -38}, {101, 101, 185}, {102, 122, 125}, },
            {{48, 113, -37}, {114, 114, 186}, {115, 122, 125}, },
            {{48, 104, -31}, {105, 105, 187}, {106, 122, 125}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{48, 57, 188}, {65, 70, 189}, {97, 102, 190}, },
            {{0, 65535, -80}, },
            {},
            {{10, 10, 191}, },
            {},
            {{0, 65535, -83}, },
            {{0, 35, 161}, {36, 36, 192}, {37, 65535, 161}, },
            {},
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{48, 57, 193}, {65, 70, 194}, {97, 102, 195}, },
            {{48, 57, 196}, {65, 70, 197}, {97, 102, 198}, },
            {{48, 102, -174}, },
            {{48, 102, -174}, },
            {{48, 122, -24}, },
            {{48, 113, -37}, {114, 114, 199}, {115, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 100, -38}, {101, 101, 200}, {102, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 103, -30}, {104, 104, 201}, {105, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 116, -33}, {117, 117, 202}, {118, 122, 125}, },
            {{48, 109, -28}, {110, 110, 203}, {111, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 107, -32}, {108, 108, 204}, {109, 122, 125}, },
            {{48, 57, 205}, {65, 70, 206}, {97, 102, 207}, },
            {{48, 102, -190}, },
            {{48, 102, -190}, },
            {},
            {},
            {{48, 57, 208}, {65, 70, 209}, {97, 102, 210}, },
            {{48, 102, -195}, },
            {{48, 102, -195}, },
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 104, -31}, {105, 105, 211}, {106, 122, 125}, },
            {{48, 113, -37}, {114, 114, 212}, {115, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 100, -38}, {101, 101, 213}, {102, 122, 125}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{32, 126, -8}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{39, 39, 163}, },
            {{48, 109, -28}, {110, 110, 214}, {111, 122, 125}, },
            {{48, 109, -28}, {110, 110, 215}, {111, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 102, 125}, {103, 103, 216}, {104, 122, 125}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {0, 0, 0, 0, 0, 0, -1, 28, 2, -1, 34, 35, 27, 26, 40, 25, 21, 42, 41, 30, 29, 31, 20, 36, -1, 37, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 38, 39, 0, -1, -1, 24, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 22, 22, 22, 43, 32, 33, 20, 20, 20, 20, 1, 1, 1, 1, 1, 1, 1, -1, 20, 20, 20, 6, 20, 20, 9, 20, 20, 20, 14, 20, 20, 20, 20, -1, -1, -1, -1, -1, -1, -1, -1, 2, 2, 2, 2, -1, -1, 23, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, 20, 5, 20, 8, 10, 11, 12, 15, 20, 20, 18, 20, -1, -1, -1, 2, 2, -1, -1, -1, 1, 1, 1, 4, 7, 20, 20, 17, 20, -1, -1, -1, -1, -1, -1, 20, 20, 19, 20, 16, 13, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
