/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AIfHeaderExpr extends PExpr
{
    private PExpr _cond_;

    public AIfHeaderExpr()
    {
        // Constructor
    }

    public AIfHeaderExpr(
        @SuppressWarnings("hiding") PExpr _cond_)
    {
        // Constructor
        setCond(_cond_);

    }

    @Override
    public Object clone()
    {
        return new AIfHeaderExpr(
            cloneNode(this._cond_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfHeaderExpr(this);
    }

    public PExpr getCond()
    {
        return this._cond_;
    }

    public void setCond(PExpr node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond_ == oldChild)
        {
            setCond((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
