/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AIntTerm extends PTerm
{
    private PPlusOrMinus _plusOrMinus_;
    private TIntegers _integers_;

    public AIntTerm()
    {
        // Constructor
    }

    public AIntTerm(
        @SuppressWarnings("hiding") PPlusOrMinus _plusOrMinus_,
        @SuppressWarnings("hiding") TIntegers _integers_)
    {
        // Constructor
        setPlusOrMinus(_plusOrMinus_);

        setIntegers(_integers_);

    }

    @Override
    public Object clone()
    {
        return new AIntTerm(
            cloneNode(this._plusOrMinus_),
            cloneNode(this._integers_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntTerm(this);
    }

    public PPlusOrMinus getPlusOrMinus()
    {
        return this._plusOrMinus_;
    }

    public void setPlusOrMinus(PPlusOrMinus node)
    {
        if(this._plusOrMinus_ != null)
        {
            this._plusOrMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusOrMinus_ = node;
    }

    public TIntegers getIntegers()
    {
        return this._integers_;
    }

    public void setIntegers(TIntegers node)
    {
        if(this._integers_ != null)
        {
            this._integers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integers_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusOrMinus_)
            + toString(this._integers_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusOrMinus_ == child)
        {
            this._plusOrMinus_ = null;
            return;
        }

        if(this._integers_ == child)
        {
            this._integers_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusOrMinus_ == oldChild)
        {
            setPlusOrMinus((PPlusOrMinus) newChild);
            return;
        }

        if(this._integers_ == oldChild)
        {
            setIntegers((TIntegers) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
