/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ALocalDef2LocalDef extends PLocalDef
{
    private PFunDec _funDec_;

    public ALocalDef2LocalDef()
    {
        // Constructor
    }

    public ALocalDef2LocalDef(
        @SuppressWarnings("hiding") PFunDec _funDec_)
    {
        // Constructor
        setFunDec(_funDec_);

    }

    @Override
    public Object clone()
    {
        return new ALocalDef2LocalDef(
            cloneNode(this._funDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALocalDef2LocalDef(this);
    }

    public PFunDec getFunDec()
    {
        return this._funDec_;
    }

    public void setFunDec(PFunDec node)
    {
        if(this._funDec_ != null)
        {
            this._funDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funDec_ == child)
        {
            this._funDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funDec_ == oldChild)
        {
            setFunDec((PFunDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
