/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ANoElseIfTrail extends PIfTrail
{
    private PStmt _then_;

    public ANoElseIfTrail()
    {
        // Constructor
    }

    public ANoElseIfTrail(
        @SuppressWarnings("hiding") PStmt _then_)
    {
        // Constructor
        setThen(_then_);

    }

    @Override
    public Object clone()
    {
        return new ANoElseIfTrail(
            cloneNode(this._then_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoElseIfTrail(this);
    }

    public PStmt getThen()
    {
        return this._then_;
    }

    public void setThen(PStmt node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._then_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._then_ == oldChild)
        {
            setThen((PStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
