/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import java.util.*;
import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PFunDef> _funDef_ = new LinkedList<PFunDef>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _funDef_)
    {
        // Constructor
        setFunDef(_funDef_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._funDef_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PFunDef> getFunDef()
    {
        return this._funDef_;
    }

    public void setFunDef(List<?> list)
    {
        for(PFunDef e : this._funDef_)
        {
            e.parent(null);
        }
        this._funDef_.clear();

        for(Object obj_e : list)
        {
            PFunDef e = (PFunDef) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._funDef_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funDef_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funDef_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PFunDef> i = this._funDef_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFunDef) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
