/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AStmtReturnstmtStmtWithElse extends PStmtWithElse
{
    private PReturnstmt _returnstmt_;

    public AStmtReturnstmtStmtWithElse()
    {
        // Constructor
    }

    public AStmtReturnstmtStmtWithElse(
        @SuppressWarnings("hiding") PReturnstmt _returnstmt_)
    {
        // Constructor
        setReturnstmt(_returnstmt_);

    }

    @Override
    public Object clone()
    {
        return new AStmtReturnstmtStmtWithElse(
            cloneNode(this._returnstmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtReturnstmtStmtWithElse(this);
    }

    public PReturnstmt getReturnstmt()
    {
        return this._returnstmt_;
    }

    public void setReturnstmt(PReturnstmt node)
    {
        if(this._returnstmt_ != null)
        {
            this._returnstmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._returnstmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._returnstmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._returnstmt_ == child)
        {
            this._returnstmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._returnstmt_ == oldChild)
        {
            setReturnstmt((PReturnstmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
