/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ATerm4Term extends PTerm
{
    private PFunCal _funCal_;

    public ATerm4Term()
    {
        // Constructor
    }

    public ATerm4Term(
        @SuppressWarnings("hiding") PFunCal _funCal_)
    {
        // Constructor
        setFunCal(_funCal_);

    }

    @Override
    public Object clone()
    {
        return new ATerm4Term(
            cloneNode(this._funCal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATerm4Term(this);
    }

    public PFunCal getFunCal()
    {
        return this._funCal_;
    }

    public void setFunCal(PFunCal node)
    {
        if(this._funCal_ != null)
        {
            this._funCal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funCal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funCal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funCal_ == child)
        {
            this._funCal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funCal_ == oldChild)
        {
            setFunCal((PFunCal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
