/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ATerm3Term extends PTerm
{
    private PLVal _lVal_;

    public ATerm3Term()
    {
        // Constructor
    }

    public ATerm3Term(
        @SuppressWarnings("hiding") PLVal _lVal_)
    {
        // Constructor
        setLVal(_lVal_);

    }

    @Override
    public Object clone()
    {
        return new ATerm3Term(
            cloneNode(this._lVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATerm3Term(this);
    }

    public PLVal getLVal()
    {
        return this._lVal_;
    }

    public void setLVal(PLVal node)
    {
        if(this._lVal_ != null)
        {
            this._lVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lVal_ == child)
        {
            this._lVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lVal_ == oldChild)
        {
            setLVal((PLVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
