/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AVarDec1VarDec extends PVarDec
{
    private TVara _vara_;
    private PVarIds _varIds_;
    private TColon _colon_;
    private PVarType _varType_;
    private TSemi _semi_;

    public AVarDec1VarDec()
    {
        // Constructor
    }

    public AVarDec1VarDec(
        @SuppressWarnings("hiding") TVara _vara_,
        @SuppressWarnings("hiding") PVarIds _varIds_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PVarType _varType_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setVara(_vara_);

        setVarIds(_varIds_);

        setColon(_colon_);

        setVarType(_varType_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AVarDec1VarDec(
            cloneNode(this._vara_),
            cloneNode(this._varIds_),
            cloneNode(this._colon_),
            cloneNode(this._varType_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDec1VarDec(this);
    }

    public TVara getVara()
    {
        return this._vara_;
    }

    public void setVara(TVara node)
    {
        if(this._vara_ != null)
        {
            this._vara_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vara_ = node;
    }

    public PVarIds getVarIds()
    {
        return this._varIds_;
    }

    public void setVarIds(PVarIds node)
    {
        if(this._varIds_ != null)
        {
            this._varIds_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varIds_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PVarType getVarType()
    {
        return this._varType_;
    }

    public void setVarType(PVarType node)
    {
        if(this._varType_ != null)
        {
            this._varType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varType_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vara_)
            + toString(this._varIds_)
            + toString(this._colon_)
            + toString(this._varType_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vara_ == child)
        {
            this._vara_ = null;
            return;
        }

        if(this._varIds_ == child)
        {
            this._varIds_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._varType_ == child)
        {
            this._varType_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vara_ == oldChild)
        {
            setVara((TVara) newChild);
            return;
        }

        if(this._varIds_ == oldChild)
        {
            setVarIds((PVarIds) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._varType_ == oldChild)
        {
            setVarType((PVarType) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
