/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AWhileStmtWithElse extends PStmtWithElse
{
    private PWhileWithElse _whileWithElse_;

    public AWhileStmtWithElse()
    {
        // Constructor
    }

    public AWhileStmtWithElse(
        @SuppressWarnings("hiding") PWhileWithElse _whileWithElse_)
    {
        // Constructor
        setWhileWithElse(_whileWithElse_);

    }

    @Override
    public Object clone()
    {
        return new AWhileStmtWithElse(
            cloneNode(this._whileWithElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileStmtWithElse(this);
    }

    public PWhileWithElse getWhileWithElse()
    {
        return this._whileWithElse_;
    }

    public void setWhileWithElse(PWhileWithElse node)
    {
        if(this._whileWithElse_ != null)
        {
            this._whileWithElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileWithElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileWithElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileWithElse_ == child)
        {
            this._whileWithElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileWithElse_ == oldChild)
        {
            setWhileWithElse((PWhileWithElse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
