/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AWhilestmtStmt extends PStmt
{
    private PWhilestmt _whilestmt_;

    public AWhilestmtStmt()
    {
        // Constructor
    }

    public AWhilestmtStmt(
        @SuppressWarnings("hiding") PWhilestmt _whilestmt_)
    {
        // Constructor
        setWhilestmt(_whilestmt_);

    }

    @Override
    public Object clone()
    {
        return new AWhilestmtStmt(
            cloneNode(this._whilestmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhilestmtStmt(this);
    }

    public PWhilestmt getWhilestmt()
    {
        return this._whilestmt_;
    }

    public void setWhilestmt(PWhilestmt node)
    {
        if(this._whilestmt_ != null)
        {
            this._whilestmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whilestmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whilestmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whilestmt_ == child)
        {
            this._whilestmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whilestmt_ == oldChild)
        {
            setWhilestmt((PWhilestmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
