
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 14;
  public static final int MOD = 16;
  public static final int ELSE = 4;
  public static final int PLUS = 12;
  public static final int RPAREN = 6;
  public static final int EQUAL = 9;
  public static final int IDENTIFIER = 18;
  public static final int IF = 3;
  public static final int LPAREN = 5;
  public static final int RBRAC = 8;
  public static final int COMMA = 2;
  public static final int NUMBER = 19;
  public static final int LESSTHAN = 11;
  public static final int EOF = 0;
  public static final int DIV = 15;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int LBRAC = 7;
  public static final int GREATERTHAN = 10;
  public static final int UMINUS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "IF",
  "ELSE",
  "LPAREN",
  "RPAREN",
  "LBRAC",
  "RBRAC",
  "EQUAL",
  "GREATERTHAN",
  "LESSTHAN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "UMINUS",
  "IDENTIFIER",
  "NUMBER"
  };
}

