/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AIdBracketsLVal extends PLVal
{
    private PLVal _lVal_;
    private PExpr _expr_;

    public AIdBracketsLVal()
    {
        // Constructor
    }

    public AIdBracketsLVal(
        @SuppressWarnings("hiding") PLVal _lVal_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setLVal(_lVal_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AIdBracketsLVal(
            cloneNode(this._lVal_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdBracketsLVal(this);
    }

    public PLVal getLVal()
    {
        return this._lVal_;
    }

    public void setLVal(PLVal node)
    {
        if(this._lVal_ != null)
        {
            this._lVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lVal_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lVal_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lVal_ == child)
        {
            this._lVal_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lVal_ == oldChild)
        {
            setLVal((PLVal) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
