/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ANoneFparDef extends PFparDef
{

    public ANoneFparDef()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ANoneFparDef();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoneFparDef(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
