/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import java.util.*;
import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AWithElseIfTrail extends PIfTrail
{
    private final LinkedList<PStmt> _then_ = new LinkedList<PStmt>();
    private final LinkedList<PStmt> _elseSt_ = new LinkedList<PStmt>();

    public AWithElseIfTrail()
    {
        // Constructor
    }

    public AWithElseIfTrail(
        @SuppressWarnings("hiding") List<?> _then_,
        @SuppressWarnings("hiding") List<?> _elseSt_)
    {
        // Constructor
        setThen(_then_);

        setElseSt(_elseSt_);

    }

    @Override
    public Object clone()
    {
        return new AWithElseIfTrail(
            cloneList(this._then_),
            cloneList(this._elseSt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWithElseIfTrail(this);
    }

    public LinkedList<PStmt> getThen()
    {
        return this._then_;
    }

    public void setThen(List<?> list)
    {
        for(PStmt e : this._then_)
        {
            e.parent(null);
        }
        this._then_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._then_.add(e);
        }
    }

    public LinkedList<PStmt> getElseSt()
    {
        return this._elseSt_;
    }

    public void setElseSt(List<?> list)
    {
        for(PStmt e : this._elseSt_)
        {
            e.parent(null);
        }
        this._elseSt_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._elseSt_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._then_)
            + toString(this._elseSt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._then_.remove(child))
        {
            return;
        }

        if(this._elseSt_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PStmt> i = this._then_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PStmt> i = this._elseSt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
